export const actionTypes = {
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  RECEIVE_ACCESS_TOKEN: 'RECEIVE_ACCESS_TOKEN',
  GET_USER_INFO: 'GET_USER_INFO',
  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
  UPDATE_AVATAR_USER: 'UPDATE_AVATAR_USER',
  UPDATE_EMAIL_USER: 'UPDATE_EMAIL_USER',
  UPDATE_PHONE_USER: 'UPDATE_PHONE_USER',
  UPDATE_PASSWORD_USER: 'UPDATE_PASSWORD_USER',
  CALL_API_USER: 'CALL_API_USER',

  GET_ALL_EXAM: 'GET_ALL_EXAM',
  GET_EXAM_BY_SUBJECT: 'GET_EXAM_BY_SUBJECT',
  GET_COMPLETED_EXAMS: 'GET_COMPLETED_EXAMS',
  DELETE_EXAM: 'DELETE_EXAM',
  UPDATE_EXAM: 'UPDATE_EXAM',
  CREATE_EXAM: 'CREATE_EXAM',
  GET_DETAIL_EXAM: 'GET_DETAIL_EXAM',
  CHANGE_SUBJECT: 'CHANGE_SUBJECT',
  CHANGE_HEADER: 'CHANGE_HEADER',
  CALL_API_EXAM: 'CALL_API_EXAM',
  CHANGE_ACTIVE_PAGE: 'CHANGE_ACTIVE_PAGE',
  CHANGE_ACTIVE_EXAM: 'CHANGE_ACTIVE_EXAM',
  GET_LIST_HISTORY_EXAM: 'GET_LIST_HISTORY_EXAM',

  GET_QUESTION_LIST: 'GET_QUESTION_LIST',
  GET_QUESTION_DETAIL: 'GET_QUESTION_DETAIL',
  DELETE_QUESTION: 'DELETE_QUESTION',
  UPDATE_QUESTION: 'UPDATE_QUESTION',
  CREATE_QUESTION: 'CREATE_QUESTION',
  CALL_API_QUESTION: 'CALL_API_QUESTION',
  
  SUBMIT_EXAM: 'SUBMIT_EXAM',
  // VIEW_EXAM: 'VIEW_EXAM',
  GET_RESULT_EXAM: 'GET_RESULT_EXAM',
  GET_RANK_LIST: 'GET_RANK_LIST',

  // VIEW_QUESTION: 'VIEW_QUESTION',



}