export const actionTypes = {
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  RECEIVE_ACCESS_TOKEN: 'RECEIVE_ACCESS_TOKEN',
  GET_USER_INFO: 'GET_USER_INFO',
  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
  UPDATE_AVATAR_USER: 'UPDATE_AVATAR_USER',
  UPDATE_EMAIL_USER: 'UPDATE_EMAIL_USER',
  UPDATE_PHONE_USER: 'UPDATE_PHONE_USER',
  UPDATE_PASSWORD_USER: 'UPDATE_PASSWORD_USER',

  GET_EXAM: 'GET_EXAM',
  DELETE_EXAM: 'DELETE_EXAM',
  UPDATE_EXAM: 'UPDATE_EXAM',
  CREATE_EXAM: 'CREATE_EXAM',

  GET_QUESTION: 'GET_QUESTION',
  DELETE_QUESTION: 'DELETE_QUESTION',
  UPDATE_QUESTION: 'UPDATE_QUESTION',
  CREATE_QUESTION: 'CREATE_QUESTION',

  SUBMIT_EXAM: 'SUBMIT_EXAM',
  // VIEW_EXAM: 'VIEW_EXAM',
  GET_RESULT_EXAM: 'GET_RESULT_EXAM',

  // VIEW_QUESTION: 'VIEW_QUESTION',



}